[package]
name = "mz-metrics"
description = "Metrics."
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
prometheus = { git = "https://github.com/MaterializeInc/rust-prometheus.git", default-features = false }
