{
 "title": "Materialize Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "command",
    "query": "label_values(mz_command_durations_bucket, command)"
   },
   {
    "name": "timely_workers",
    "label": "Timely Workers",
    "query": "query_result(mz_server_metadata_timely_worker_threads)"
   },
   {
    "name": "built_at",
    "label": "Built at",
    "query": "label_values(mz_server_metadata_seconds, build_time)"
   },
   {
    "name": "build_version",
    "label": "Version",
    "query": "label_values(mz_server_metadata_seconds, build_version)"
   },
   {
    "name": "build_sha",
    "label": "Git commit",
    "query": "label_values(mz_server_metadata_seconds, build_sha)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Messages Ingested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mz_messages_ingested)" }
   ]
  },
  {
   "title": "Kafka Message Ingest Rate",
   "type": "stat",
   "description": "How many messages per second materialized is currently ingesting",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_messages_ingested[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Number of Records",
   "type": "stat",
   "description": "A record is equivalent to a row in a traditional database",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mz_perf_arrangement_records)"
    }
   ]
  },
  {
   "title": "Client queries per second",
   "type": "stat",
   "description": "Total number of sql data queries being executed per second.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{command=~\"execute|query\",status=\"success\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Query Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{status=\"error\"}[5m]))",
     "legendFormat": "{{purpose}}/{{test}}/{{workflow}}/{{id}}"
    }
   ]
  },
  {
   "title": "Materialize Build Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "content": "Timely Workers: $timely_workers<br/>\nBuilt At: $built_at<br/>\nBuild Version: $build_version<br/>\nBuild SHA: $build_sha<br/>"
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "command=$command server latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "command=$command server latency quantiles",
   "type": "graph",
   "description": "the view of how long things took, from inside pgwire",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
     "legendFormat": "p001"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"error\"}[$__interval])) by (le))",
     "legendFormat": "error p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"error\"}[$__interval])) by (le))",
     "legendFormat": "error max"
    }
   ]
  },
  {
   "title": "queries/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_command_durations_count[$__interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "query rows|bytes/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_pg_sent_rows[$__interval])",
     "legendFormat": "rows/sec"
    },
    {
     "expr": "rate(mz_pg_sent_bytes[$__interval])",
     "legendFormat": "bytes/sec"
    }
   ]
  },
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Ingested by Message Format",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_dataflow_events_read_total[$__interval])",
       "legendFormat": "{{format}} events {{status}}"
      },
      {
       "expr": "mz_dataflow_events_read_total",
       "legendFormat": "{{format}} events total {{status}}"
      }
     ]
    },
    {
     "title": "Kafka Messages Ingested",
     "type": "graph",
     "description": "Unlike the Messages Ingested by Format, this shows the raw number of messages we've received\n\nCurrently only shows Kafka",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_messages_ingested[$__interval])",
       "legendFormat": "rate {{topic}} {{source_id}} {{partition_id}}"
      },
      {
       "expr": "mz_messages_ingested",
       "legendFormat": "total {{topic}} {{source_id}} {{partition_id}}"
      }
     ]
    },
    {
     "title": "Kafka Offsets Received",
     "type": "graph",
     "description": "The raw kafka offset as seen at ingest time by materialized.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mz_partition_offset_received",
       "legendFormat": "{{topic}}/{{partition_id}} {{source_id}}"
      }
     ]
    },
    {
     "title": "Kafka bytes read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_bytes_read_total[$__interval])",
       "legendFormat": "rate"
      },
      { "expr": "mz_bytes_read_total", "legendFormat": "total" }
     ]
    },
    {
     "title": "Messages behind Kafka",
     "type": "graph",
     "description": "This shows the number of messages that materialize knows it is behind an external source.\n\nFor example, if there are 1,000 messages in kafka and materialized has processed 750, this value will be 250",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(50, mz_kafka_partition_offset_max - mz_partition_offset_ingested)",
       "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
      }
     ]
    },
    {
     "title": "Source Scheduled Count",
     "type": "graph",
     "description": "The total number of times that a source has been scheduled, and the rate at which they're scheduled.\n\nIn a well-behaved system, sources should be activated approximately in proportion to how much data they have to read. If sources are being scheduled at significantly different proportions it could mean that the more-scheduled sources are having a hard time keeping up.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(mz_operator_scheduled_total[$__interval])",
       "legendFormat": "kafka {{topic}} {{source_id}}"
      },
      {
       "expr": "mz_operator_scheduled_total",
       "legendFormat": "kafka total {{topic}} {{source_id}}"
      }
     ]
    },
    {
     "title": "Time behind external source",
     "type": "graph",
     "description": "This is only reported for Kinesis sources at the moment.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "mz_kinesis_shard_millis_behind_latest",
       "legendFormat": "{{ stream_name }} {{ shard_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal Latency Measures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontier lags",
     "type": "graph",
     "description": "This shows the top 10 dataflow operators that are introducing lag into the system.\n\nAn operator can introduce lag either because its source is running behind, or because it is doing lots of work.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms", "label": "Lag (from -> to)" }
     ],
     "targets": [
      {
       "expr": "topk(10, mz_perf_dependency_frontiers)",
       "legendFormat": "{{source}} -> {{dataflow}}"
      }
     ]
    },
    {
     "title": "Worker queue sizes",
     "type": "graph",
     "description": "A worker is the underlying thread of computation in materialized. In general materialized should send similar amounts of work to each worker, and the queue depths should be similar to each other.\n\nIf a queue is growing without bound, or queues are very unbalanced, that could signify a problem.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mz_worker_command_queue_size",
       "legendFormat": "pending commands worker={{worker}}"
      },
      {
       "expr": "mz_worker_pending_peeks_queue_size",
       "legendFormat": "pending peeks worker={{worker}}"
      }
     ]
    },
    {
     "title": "Timestamp Closing Lag",
     "type": "graph",
     "description": "(top 10 most laggy)\n\nIn a healthy system this should converge to a value that oscillates between 0 and the configured timestamp frequency.\n\nUnder the hood, this is the difference between allocated timestamps and closed timestamps.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(10, (mz_max_timestamp - ignoring(topic) mz_partition_closed_ts))",
       "legendFormat": "{{source_id}}-{{partition_id}}"
      }
     ]
    },
    {
     "title": " Capability Closing Rate",
     "type": "graph",
     "description": "This is a measure of when we last stated that ingested data was valid for computation. Another way of thinking about this is how many seconds of data do we ingest per second of real time. In a steady state this should be approximately 1s/s.\n\nAll sources that have a rate of 0 are *stalled* and are either not ingesting new data or have no new data to ingest.\n\nInternally, this is the capability, and the underlying measure is what capability we have released.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(mz_capability[$__interval])",
       "legendFormat": "{{topic}}-{{source_id}}"
      }
     ]
    },
    {
     "title": "Partition Imbalance Amount",
     "type": "graph",
     "description": "The difference between the most-consumed and least-consumed kafka partition, in terms of when we last released messages into the dataflow layer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (topic, source_id) (mz_partition_closed_ts) - min by (topic, source_id) (mz_partition_closed_ts)",
       "legendFormat": "{{topic}}-{{source_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "materialized: resident memory",
     "type": "graph",
     "description": "See also the Memory/Meminfo row in the [node-state dashboard](/d/node-state?var-job=load_test). \n\nYou will need to filter to the current instance: $instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "materialized: CPU usage",
     "type": "graph",
     "description": "See also the CPU row in the [node-state dashboard](/d/node-state?var-job=load_test). \n\nYou will need to filter to the current instance: $instances",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\".*:6875\"}[$__interval])",
       "legendFormat": "materialized"
      },
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\".*16875\"}[$__interval])",
       "legendFormat": "peeker"
      }
     ]
    },
    {
     "title": "Arrangement Batches",
     "type": "graph",
     "description": "A batch is a slab of memory, arrangements with a large number of batches have allocated a large number of records, which should be represented in the Arrangement Records panel.\n\nThis shows the top 10 arrangements by number of batches, and should be similar to the Arrangement Records panel.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, mz_perf_arrangements_batches)",
       "legendFormat": "w={{worker}} op={{operator}}"
      }
     ]
    },
    {
     "title": "Arrangement Records",
     "type": "graph",
     "description": "An arrangement is where materialize stores state, records are equivalent to rows in a database or messages in a stream.\n\nThis shows the top 10 arrangements by number of records, and should be similar to the Arrangement Batches panel.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, mz_perf_arrangement_records)",
       "legendFormat": "w={{worker}} op={{operator}} name={{name}}"
      }
     ]
    }
   ]
  }
 ]
}