[package]
name = "mz-secrets"
description = "Abstractions for secure management of secrets."
version = "0.0.0"
edition = "2021"
rust-version = "1.61.0"
publish = false

[dependencies]
anyhow = "1.0.57"
mz-repr = { path = "../repr" }
async-trait = "0.1.56"
